FROM erickbrower/docker-java

RUN wget -O ruby-install-0.4.0.tar.gz --no-check-certificate https://github.com/postmodern/ruby-install/archive/v0.4.0.tar.gz
RUN tar -xzvf ruby-install-0.4.0.tar.gz && cd ruby-install-0.4.0 && make install
