FROM ubuntu:13.10

RUN apt-get update && apt-get install -y build-essential wget curl libcurl3 libcurl3-gnutls libcurl4-openssl-dev libffi-dev \
    libffi6 libgdbm-dev libgvc5 libmagickwand-dev imagemagick libncurses5 libncurses5-dev libncurses5-dbg \
    libossp-uuid-dev libpq-dev libmysqlclient-dev libreadline6 libreadline6-dev libssl-dev libyaml-0-2 libyaml-dev \
    libtool mysql-client zlib1g zlib1g-dev postgresql-client-9.1 software-properties-common python-software-properties socat
